spring:
  application:
    name: Monitoring-Boilerplate
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/monitoring-boilerplate;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 200
    defer-datasource-initialization: true

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: health, prometheus